name: Build debug APK

on:
  workflow_dispatch:
  push:
    branches:
      - 11-dev

jobs:
  build-debug-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true
      - name: Set up Java 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Grant execution permission to Gradle Wrapper
        run: chmod +x gradlew
      - name: Build debug APK
        run: ./gradlew assembleLawnWithQuickstepDebug
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Lawnchair
          path: build/outputs/apk/lawnWithQuickstep/debug/**.apk